sudo: required
language: bash
env:
  global:
  - LIVE_SERVICE=todo-service
  - LIVE_CLUSTER_NAME=ees-server-cluster-1  
  - LIVE_APP_NAME=todo
  - AWS_URL=450447634754.dkr.ecr.ap-southeast-2.amazonaws.com
  - secure: jEuO7N8fBJLQHWUOdg5x2POy757h+R4n50w6Z+7pTMIIO8N8q7o66qbw6pvFK/raE+rxDRkKznMYDmnsVJum4NAe3+7Xt3TvshLYtST16Jxkyhg5pNYILH9Xp4WcVPoGlNSHKw+Xq2PjwU/VYYeURCMhkPOhCwjOKwsA+/jIM5vTbUrtOko0qlHjnSaTH2/SHaihaNQJ1tr/LguklV0BgD0FUdQor2Aska1JKlh5njX5BuiWfHft3TMCkgCTj2Ow7RUN/iFqhfLOO+MvylJ8/wazqzii2xL2LXXyBHR9Dh2FFsb7ZGBmnWe0F1GArJwmcYGjcBrUqDZEYDFb86793SsdHIBCFF6mnGK+QP1qDFiu8Gz5Ger/jjF49e0eJ5PrhZDO/3FXCahHJS0ZxIv3CgV4YQghdmHulQ7nbeT7LC3ZlKFle8eiJ35VW6MbT6jcqh5ru5SFrqfX0FoE7Rk/Bv27MVSCzj1o89ikhOeooJ+E807CzXZbli9qHv5DxIbixLpHROz1+HlkWyaZ6+CBA3nbXiOW7Q/9ppaffSHw/zRhpJcjmKy+S4sr9rY6GP6EPDXTNWBdcDi8JfKaKgQDT3U+gj02+L3NijbMXVr7FQuiGz+ndZHW9Dq2D03XOG3iaR5WMEBRvIbyDYa2HldDLC3jXVjUWipDdzuZLwqff1s=
  - secure: GTXkMax+uZ7AMivXjVzq8SPN4EnRA0TWn95+k772IYjoCQ813NVBmZP/8fEiQpvEQAWtcrktPB25QbZ9/5iHosSdLiYEkYi7WhfQx69Qro9LomcA7hBukcS9wowUFZ6623PrhbEZrro4gkFAi3OsZCH5Sb4lpFv1P8rtiQKFW8mVX/poCEDukTUj8p9dQUN9ahppyDEBp2EmNxSWQzo0kPV+/myLvKdPBk16f8JWZM4r+tr/PKfSbjLzyPrviqKUDHY1nME84dyPxMAntTkVJ7FeHx1bqyzo3aUTMV8sfyGS8TeETuiKFzSoH2+H3xxp9AIXIVW0xwyhan0frM1sF7jJZCmtPd1rop620pdl04gdQcVWQ9ip8A3wLUubL/LdWIGrn84WIJ7fi7lvkzonjReUuCTtiSmDC6mcvmg0BuIKFAMdiOW/hhTW8v5fpQG70eXuOkxKfqoJbe6a6r/RJ+2mPmPnSYk42dxxudpBtD38y2HLPAoFRXldVivSIdDLgUSPn6hhbcsVVMcgC2L5i6JdJg487K63DKpTNm4OppJJc/GlI2gXc2HHl8Tkvft1T7+/2eGX7CYxZcweS4RLHOtsNm6pbJpisd/ps1VPkPOBhI8PQQrwKvBtF/bDfpeeC3mhrxzebBF6dmuvWUKZ0s9Lu7pjhvk6hE+s/Pvb94Q=
services:
- docker
script:
- npm test
after_success:
- bash docker_push.sh
- bash ecs_deploy.sh
